#: Short to long names for columns in survey
names = {
    "timestamp"                      : "Timestamp",
    "user_type"                      : "What kind of user are you?",
    "workplace"                      : "Where do you work?",
    "country"                        : "What country are you in?",
    "in_ecp"                         : "Are you part of the U.S. Exascale Computing Project (ECP)?",
    "app_area"                       : "What are your primary application areas?",
    "how_find_out"                   : "How did you find out about Spack?",
    "how_long_using"                 : "How long have you been using Spack?",
    "how_contributed"                : "Have you contributed to Spack?",
    "spack_versions"                 : "What version(s) of Spack do you use?",
    "os"                             : "What OS do you use Spack on?",
    "num_installations"              : "How many software installations have you done with Spack in the past year?",
    "python_version"                 : "What Python version(s) do you use to run Spack?",
    "how_bad_no_py26"                : "How bad would it be if Spack dropped support for Python 2.6?",
    "how_bad_only_py3"               : "How bad would it be if Spack ONLY worked with Python 3?",
    "how_use_pkgs"                   : "How do you get installed Spack packages into your environment?",
    "used_features"                  : "Which of the following Spack features do you use?",
    "cpus_next_year"                 : "Which processors do you expect to use with Spack in the next year?",
    "gpus_next_year"                 : "Which GPUs do you expect to use with Spack in the next year?",
    "compilers_next_year"            : "Which compilers do you expect to use with Spack in the next year?",

    "feature_new_concretizer"        : "Rank these TBD Spack features by importance [New, backtracking concretizer]",
    "feature_use_existing_installs"  : "Rank these TBD Spack features by importance [Use existing installs more aggressively]",
    "feature_separate_build_deps"    : "Rank these TBD Spack features by importance [Separate concretization of build dependencies ]",
    "feature_cloud_integration"      : "Rank these TBD Spack features by importance [AWS/Azure/GCP/Cloud integration]",
    "feature_optimized_binaries"     : "Rank these TBD Spack features by importance [Optimized, public binary packages]",
    "feature_developer_support"      : "Rank these TBD Spack features by importance [Better Developer features (easily develop multiple packages + 3rd party dependencies)]",
    "feature_pkg_notifications"      : "Rank these TBD Spack features by importance [Notifications about changes to my packages]",
    "feature_build_testing"          : "Rank these TBD Spack features by importance [Build testing for every PR]",
    "feature_language_virtuals"      : 'Rank these TBD Spack features by importance [Language virtual dependencies (e.g., depends_on("cxx@2017:"))]',
    "feature_testing"                : "Rank these TBD Spack features by importance [Testing / integration with Pavilion2/ReFrame/other test tool]",
    "feature_better_flag_handling"   : "Rank these TBD Spack features by importance [Better compiler flag handling]",
    "feature_windows"                : "Rank these TBD Spack features by importance [Windows Support]",
    "feature_custom"                 : "What features NOT in the prior list would you like to see?",

    "would_attend_workshop"          : "If we had a (virtual) workshop on Spack, would you attend?",
    "did_tutorial"                   : "Have you done a Spack Tutorial?",
    "how_get_help"                   : "How do you get help with Spack when you need it?",
    "how_often_docs"                 : "How often do you consult the Spack documentation?",
    "commercial_support"             : "If there were commercial support for Spack, would you or your organization buy it?",

    "quality_docs"                   : "How would you rate the overall quality of ... [Spack documentation]",
    "quality_community"              : "How would you rate the overall quality of ... [Spack community]",
    "quality_packages"               : "How would you rate the overall quality of ... [Spack packages]",
    "quality_spack"                  : "How would you rate the overall quality of ... [Spack]",

    "long_workflow"                  : "Tell us briefly about your use case and your usual Spack workflow.",
    "long_what_helps_most"           : "What about Spack helps you the most?",
    "long_pain_points"               : "What are the biggest pain points in Spack for your workflow? (feel free to link to issues)",
    "long_best_improvement"          : "What's the biggest thing we could do to improve Spack over the next year?",
    "long_desired_packages"          : "Are there key packages you'd like to see in Spack that are not included yet?",
    "long_other_comments"            : "Do you have any other comments for us?",

    "email"                          : "If you're interested in being contacted about your response, please leave us your email.",
    "edit_url"                       : "Form Response Edit URL",
}

description_to_name = {names[n]: n for n in names}
